aaa_standard = "SSP1"
aaa_namespace = "ssv"
aaa_name = "SystemStructureParameterValues"
aaa_dependencies = ["SSP1_SystemStructureCommon"]


[Real]
value = { type = "double"}
unit = { type = "string", optional = true }

[Integer]
value = { type = "int" }

[Boolean]
value = { type = "bool" }

[String]
value = { type = "string" }

[Enumeration]
value = { type = "string" }
name = { type = "string", optional = true }

[Binary]
value = { type = "string" }
mime_type = { type = "string", optional = true, xml_tag="mime-type" }


[TParameter]
id = {type = "string", optional = true}
description = {type = "string", optional = true}
name = {type = "string"}
Real = { type = "ssv::Real", optional = true}
Integer = { type = "ssv::Integer", optional = true}
Boolean = { type = "ssv::Boolean", optional = true}
String = { type = "ssv::String", optional = true}
Enumeration = { type = "ssv::Enumeration", optional = true}
Binary = { type = "ssv::Binary", optional = true}
Annotations = {type = "ssc::TAnnotations", optional = true, namespace="ssc"}

[TParameters]
Parameters = {type = "ssv::TParameter", list = true, namespace="ssv"}

[ParameterSet]
version = {type = "string"}
name = {type = "string"}
id = {type = "string", optional = true}
description = {type = "string", optional = true}
author = {type = "string", optional = true}
fileversion = {type = "string", optional = true}
copyright = {type = "string", optional = true}
license = {type = "string", optional = true}
generationTool = {type = "string", optional = true}
generationDateAndTime = {type = "string", optional = true}
TParameters = {type = "ssv::TParameters", namespace="ssv"}
Enumerations = {type = "ssc::TEnumerations", optional = true, namespace="ssc"}
Units = {type = "ssc::TUnits", optional = true, namespace="ssc"}
Annotations = {type = "ssc::TAnnotations", optional = true, namespace="ssc"}
