aaa_standard = "SSP1"
aaa_namespace = "ssm"
aaa_name = "SystemStructureParameterMapping"
aaa_dependencies = ["SSP1_SystemStructureCommon"]



[TMappingEntry]
id = {type = "string", optional = true}
description = {type = "string", optional = true}
source = {type = "string"}
target = {type = "string"}
suppressUnitConversion = {type = "bool", optional = true}
LinearTransformation = {type = "ssc::LinearTransformation", optional=true, namespace="ssc"}
BooleanMappingTransformation = {type = "ssc::BooleanMappingTransformation", optional=true, namespace="ssc"}
IntegerMappingTransformation = {type = "ssc::IntegerMappingTransformation", optional=true, namespace="ssc"}
EnumerationMappingTransformation = {type = "ssc::EnumerationMappingTransformation", optional=true, namespace="ssc"}
Annotations = {type = "ssc::TAnnotations", optional = true, namespace="ssc"}

[ParameterMapping]
version = {type = "string"}
id = {type = "string", optional = true}
description = {type = "string", optional = true}
author = {type = "string", optional = true}
fileversion = {type = "string", optional = true}
copyright = {type = "string", optional = true}
license = {type = "string", optional = true}
generationTool = {type = "string", optional = true}
generationDateAndTime = {type = "string", optional = true}
MappingEntry = {type = "ssm::TMappingEntry", list=true, namespace="ssm"}
Annotations = {type = "ssc::TAnnotations", optional = true, namespace="ssc"}
